package silverspoon;

import java.awt.*;
import java.net.*;
import java.io.*;
import javax.swing.*;

import com.kitfox.svg.*;
import com.kitfox.svg.app.beans.*;
import java.util.LinkedList;

class IconPanel extends JPanel {

    public static final long serialVersionUID = 0;

    final SVGIcon icon;

    private String config;

    public IconPanel(String c) {
        StringReader reader = new StringReader(c);
        URI uri = SVGCache.getSVGUniverse().loadSVG(reader, "myImage");
        icon = new SVGIcon();
        icon.setSvgURI(uri);

        setPreferredSize(new Dimension(555, 354));
    }

    public void paintComponent(Graphics g) {
        final int width = getWidth();
        final int height = getHeight();

        g.setColor(getBackground());
        g.fillRect(0, 0, width, height);

        icon.paintIcon(this, g, 0, 0);
    }

}

/**
 *
 * @author kitfox
 */
public class SvgBuilder extends javax.swing.JFrame {

    public static final long serialVersionUID = 0;

    IconPanel panel;

    private String PrepareSvg(LinkedList<String> config) {
        int NumberOfBoxes = config.size();
        int rows = (NumberOfBoxes / 4) + (NumberOfBoxes % 4 == 0 ? 0 : 1);

        int x = 65;
        int y = 0;
        switch(rows){
            case 1: y = 160;break;
            case 2: y = 130;break;
            case 3: y = 100;break;
        }
        switch(NumberOfBoxes){
            case 1: x = 200;break;
            case 2: x = 160;break;
            case 3: x = 140;break;
        }
        String result;
        result = "<svg width=\"555\" height=\"354\">\n"
                + "\n"
                + "  <rect x=\"0\" y=\"0\" rx=\"20\" ry=\"20\" width=\"544\" height=\"354\"\n"
                + "  style=\"fill:rgb(0,122,6);stroke:black;stroke-width:0;opacity:1\"/>\n"
                + "\n"
                + "  <rect x=\"46\" y=\"85\" rx=\"0\" ry=\"0\" width=\"380\" height=\"188\"\n"
                + "  style=\"fill:rgb(51,51,51);stroke:black;stroke-width:0;opacity:1\"/>\n"
                + "\n";
               // + "    <circle cx=\"194\" cy=\"156\" r=\"19\" fill=\"rgb(184,177,128)\"/>\n"
        // + "    <circle cx=\"194\" cy=\"156\" r=\"8\" fill=\"white\"/>\n";
        int counter = 1;
        for (int j = 0; j < rows; j++) {
            for (int i = 0; i < 4; i++) {
                if (counter > NumberOfBoxes)
                    break;
                counter++;
                result += "<rect x=\"" + x + "\" y=\"" + y + "\" rx=\"0\" ry=\"0\" width=\"70\" height=\"40\"\n"
                        + "style=\"fill:rgb(255,255,255);stroke:black;stroke-width:0;opacity:1\"/>\n";
                result += "<text x=\"" + (x+15) + "\" y=\"" + (y+23) + "\">" + config.pop() + "</text>";
                x += 90;    
            
                
            }
            x = 65;
            y += 60;
        }

        result += "</svg>";
        return result;
    }

    /**
     * Creates new form SVGIconDemo
     *
     * @param Config
     */
    public SvgBuilder(LinkedList<String> config) {
        panel = new IconPanel(PrepareSvg(config));

        initComponents();

        this.getContentPane().add(panel, BorderLayout.CENTER);

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }

    public static void main(String args[]) {
        final LinkedList<String> list = new LinkedList<>();
        list.add("box1");
        list.add("box2");
        list.add("box2");
        list.add("box2");list.add("tomin");
        list.add("box1");
        list.add("box2");
        list.add("box2");
        //list.add("box2");list.add("tomin");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SvgBuilder(list).setVisible(true);
            }
        });
    }

}
